### ISSUE TITLE
nodetool can't working

### ISSUE THREAD

**Issue by esayr** [edib-tool/docker-edib-tool#16]
I build an docker image and start it with `docker run -d`, but I found nodetool can't working

```bash
root@iZbp1bhbv50pqda6ke2su6Z:~# docker ps
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                      NAMES
bdbf77a31eb3        local/edib-dev   "/bin/sh -c 'trap ..."   2 hours ago         Up 2 hours          127.0.0.1:4124->4124/tcp   test-0.0.6-4124

root@iZbp1bhbv50pqda6ke2su6Z:~# curl  http://127.0.0.1:4124
OK v0.0.6 09121026 test@10.8.5.2

root@iZbp1bhbv50pqda6ke2su6Z:~# docker exec -it bdbf77a31eb3 sh
/ # /app/bin/test attach
Node is not running!

/ # /app/bin/mglrsbackend ping
Node 'test@10.8.5.2' not responding to pings.
```

**Comment by asaaki** [comment]
If you use `/app/bin/my_app remote_console` you should be able to interact with the app.
I don't know why `attach` is not working, would need to investigate erlang release magic here.

BTW from the `attach.sh`:

```sh
# Attaches to the release console as started via `start`
# NOTE: This is not a remote console, it's the shell of the running node,
# so killing the shell will kill the node as well.
```

So I'd even recommend to use the `remote_console` command over `attach` to avoid accidental node kills. (Unless this is exactly your use case here.)

**Comment by asaaki** [comment]
Investigation Notes:

```sh
/ # /app/bin/edib_app_test attach
Can't access pipe directory /app/var/erl_pipes/edib_app_test@127.0.0.1/: No such file or directory
/ # mkdir -p /app/var/erl_pipes/edib_app_test@127.0.0.1/
/ # /app/bin/edib_app_test attach
No running Erlang on pipe /app/var/erl_pipes/edib_app_test@127.0.0.1/erlang.pipe: No such file or directory
```

Need to figure out this `erl_pipes` stuff …

**Comment by asaaki** [comment]
According to the [comment here](https://github.com/emqtt/emqttd/issues/1012#issuecomment-296517246) it might be that's impossible by default (node started with `foreground` or `console`).

Since the docker image is intentionally started with `foreground`, you are forced to connect to the node via `remote_console` anyway. (Somebody correct me if I'm wrong here.)

Does this answer your question, @esayr?

**Comment by esayr** [comment]
@asaaki  thx
use `remote_console` return same error:

```base
/ # /app/bin/mglrsbackend remote_console
Node is not running!
````

I think this is the problem of nodetool() or escript, Because the following script will return empty
```base
/ # /app/erts-8.3/bin/escript /app/bin/nodetool -name test@10.8.5.2 -setcookie "mycooike" ping
/ # 
```


By the way, how to set the time zone in docker-edib-tool ?

**Comment by asaaki** [comment]
@esayr This is interesting. In my example app and image I have not this issue.
Do you mind describing a bit all the steps from creating your app over building the images to starting containers and trying to connect? I think we miss something in the middle or somewhere on the way.

----

> By the way, how to set the time zone in docker-edib-tool ?

The images are so slim (not only in size but w.r.t. OS cruft), they do not come with any OS timezone support. So the time you see in the app and container should be equal to the host, and ideally this should be purely UTC only if run in server environments.
There are no plans to add such support; not because of sizing issues, but the troubles TZ handling can cause.

**Comment by asaaki** [comment]
No active development.
